version: '3.7'
services:
  mysqlservice:
   image: mysql:5.7
   ports:
   - 3308:3306
   environment:
      - MYSQL_ROOT_PASSWORD=hcl
      - MYSQL_DATABASE=hcldemo
      - MYSQL_USER=hcl
      - MYSQL_PASSWORD=hcl
   volumes:
   - /s/office/mysql-data:/var/lib/mysql

  employees-app:
   build: 
    context: .
    dockerfile:  R:/devops-dba/openshift-dna-demo-mysql-master/Dockerfile
   ports:
   - "2222-2230:9099"
   deploy:
      replicas: 2
   depends_on:
      - mysqlservice
  